### ISSUE TITLE
Multiple laravel projects

### ISSUE THREAD

**Issue by barart** [thomasmoors/laravel-docker#1]
I was reading your reddit comment on a post and i ended here, my doubts are what when you want to host multiple laravel projects? I dont think create a tons of containers is suitable... what do you suggest to have only the essentials containers (php, nginx, etc.) only once and a container for each project?

**Comment by thomasmoors** [comment]
> I was reading your reddit comment on a post and i ended here, my doubts are what when you want to host multiple laravel projects? I dont think create a tons of containers is suitable... what do you suggest to have only the essentials containers (php, nginx, etc.) only once and a container for each project?

Sorry for my pretty late response.

Your question is very legit. However in what configuration you create services is always your choice. This is just an example how you can have a basic config working that is production ready. And by production ready I mean: not using php's built in webserver.
